openapi: 3.0.2
info:
  title: Fitness-Food-API
  version: 1.0.0
servers:
  - url: http://localhost
paths:
  /api:
    get:
      tags:
        - System
      summary: Show system info
      responses:
        '200':
          $ref: '#/components/responses/SystemInfo'
  /api/products:
    get:
      tags:
        - Products
      summary: Show all products paginated
      parameters:
        - name: per_page
          in: query
          description: number of products per page
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: product page number
          required: false
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ListAllProducts'
  /api/products/{product}:
    get:
      tags:
        - Products
      summary: Show a specific product
      parameters:
        - name: product
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ListProduct'
    put:
      tags:
        - Products
      summary: Update a specific product
      parameters:
        - name: product
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Product data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          $ref: '#/components/responses/ListProduct'
    delete:
      tags:
        - Products
      summary: Delete a specific product
      parameters:
        - name: product
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful response
components:
  schemas:
    Product:
      type: object
      properties:
        code:
          type: integer
        status:
          type: string
        imported_t:
          type: string
        url:
          type: string
        creator:
          type: string
        created_t:
          type: string
        last_modified_t:
          type: string
        product_name:
          type: string
        quantity:
          type: string
        brands:
          type: string
        categories:
          type: string
        labels:
          type: string
        cities:
          type: string
        purchase_places:
          type: string
        stores:
          type: string
        ingredients_text:
          type: string
        traces:
          type: string
        serving_size:
          type: string
        serving_quantity:
          type: number
        nutriscore_score:
          type: integer
        nutriscore_grade:
          type: string
        main_category:
          type: string
        image_url:
          type: string
  responses:
    SystemInfo:
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  db_connection:
                    type: string
                    example: 🟢 ON
                  db_writing:
                    type: string
                    example: 🟢 ON
                  last_cron_time:
                    type: string
                    example: '2023-02-22 19:45:27'
                  online_since:
                    type: string
                    example: up 3 hours, 12 minutes
                  memory_use:
                    type: string
                    example: 8.1Gi
      description: ''
    ListAllProducts:
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  '':
                    type: object
                    properties:
                      code:
                        type: integer
                        example: 17
                      status:
                        type: string
                        example: draft
                      imported_t:
                        type: string
                        example: '2023-02-22 22:48:33'
                      url:
                        type: string
                        example: >-
                          http://world-en.openfoodfacts.org/product/0000000000017/vitoria-crackers
                      creator:
                        type: string
                        example: fares THE DEV
                      created_t:
                        type: string
                        example: '1529059080'
                      last_modified_t:
                        type: string
                        example: '1561463718'
                      product_name:
                        type: string
                        example: Vitória crackers
                      quantity:
                        type: string
                        example: 380 g (6 x 2 u.)
                      brands:
                        type: string
                        example: La Cestera
                      categories:
                        type: string
                        example: >-
                          Lanches comida, Lanches doces, Biscoitos e Bolos,
                          Bolos, Madalenas
                      labels:
                        type: string
                        example: Contem gluten, Contém derivados de ovos, Contém ovos
                      cities:
                        type: string
                        example: Braga,Portugal
                      purchase_places:
                        type: string
                        example: Lidl
                      stores:
                        type: string
                        example: Padaria Joaquim
                      ingredients_text:
                        type: string
                        example: >-
                          farinha de trigo, açúcar, óleo vegetal de girassol,
                          clara de ovo, ovo, humidificante (sorbitol),
                          levedantes químicos (difosfato dissódico,
                          hidrogenocarbonato de sódio), xarope de
                          glucose-frutose, sal, aroma
                      traces:
                        type: string
                        example: >-
                          Frutos de casca rija,Leite,Soja,Sementes de
                          sésamo,Produtos à base de sementes de sésamo
                      serving_size:
                        type: string
                        example: madalena 31.7 g
                      serving_quantity:
                        type: number
                        example: '31.7'
                      nutriscore_score:
                        type: integer
                        example: '20'
                      nutriscore_grade:
                        type: string
                        example: d
                      main_category:
                        type: string
                        example: en:madeleines
                      image_url:
                        type: string
                        example: >-
                          https://static.openfoodfacts.org/images/products/20221126/front_pt.5.400.jpg
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: http://localhost:8080/api/products?page=1
                      last:
                        type: string
                        example: http://localhost:8080/api/products?page=450
                      prev:
                        type: string
                      next:
                        type: string
                        example: http://localhost:8080/api/products?page=2
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: string
                        example: 1
                      from:
                        type: string
                        example: 1
                      last_page:
                        type: string
                        example: 450
                      links:
                        type: object
                        properties:
                          '':
                            type: object
                            properties:
                              url:
                                type: string
                                example: http://localhost:8080/api/products?page=1
                              label:
                                type: string
                                example: 1
                              active:
                                type: string
                                example: true
                      path:
                        type: string
                        example: http://localhost:8080/api/products
                      per_page:
                        type: string
                        example: 2
                      to_page:
                        type: string
                        example: 2
                      total:
                        type: string
                        example: 900
      description: ''
    ListProduct:
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  code:
                    type: integer
                    example: 13
                  status:
                    type: string
                    example: draft
                  imported_t:
                    type: string
                    example: '2023-02-22 22:48:33'
                  url:
                    type: string
                    example: >-
                      http://world-en.openfoodfacts.org/product/0000000000017/vitoria-crackers
                  creator:
                    type: string
                    example: fares THE DEV
                  created_t:
                    type: string
                    example: '1529059080'
                  last_modified_t:
                    type: string
                    example: '1561463718'
                  product_name:
                    type: string
                    example: Vitória crackers
                  quantity:
                    type: string
                    example: 380 g (6 x 2 u.)
                  brands:
                    type: string
                    example: La Cestera
                  categories:
                    type: string
                    example: >-
                      Lanches comida, Lanches doces, Biscoitos e Bolos, Bolos,
                      Madalenas
                  labels:
                    type: string
                    example: Contem gluten, Contém derivados de ovos, Contém ovos
                  cities:
                    type: string
                    example: Braga,Portugal
                  purchase_places:
                    type: string
                    example: Lidl
                  stores:
                    type: string
                    example: Padaria Joaquim
                  ingredients_text:
                    type: string
                    example: >-
                      farinha de trigo, açúcar, óleo vegetal de girassol, clara
                      de ovo, ovo, humidificante (sorbitol), levedantes químicos
                      (difosfato dissódico, hidrogenocarbonato de sódio), xarope
                      de glucose-frutose, sal, aroma
                  traces:
                    type: string
                    example: >-
                      Frutos de casca rija,Leite,Soja,Sementes de
                      sésamo,Produtos à base de sementes de sésamo
                  serving_size:
                    type: string
                    example: madalena 31.7 g
                  serving_quantity:
                    type: number
                    example: '31.7'
                  nutriscore_score:
                    type: integer
                    example: '20'
                  nutriscore_grade:
                    type: string
                    example: d
                  main_category:
                    type: string
                    example: en:madeleines
                  image_url:
                    type: string
                    example: >-
                      https://static.openfoodfacts.org/images/products/20221126/front_pt.5.400.jpg
      description: ''
  securitySchemes:
    FitnessFoodApiKey:
      name: FitnessFoodsApiKey
      in: header
      type: apiKey
security:
  - FitnessFoodApiKey: []
tags:
  - name: System
    description: Application info
  - name: Products
    description: Products management
